config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/search'

  get 'welcome/match'

  get 'welcome/faq'

  get 'welcome/pricing'

  get 'welcome/features'

  resources :authorized_users

  root to: 'welcome#index'
end

app/models/authorized_user.rb
class AuthorizedUser < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authorized_users_controller.rb
class AuthorizedUsersController < ApplicationController
  before_action :set_authorized_user, only: [:show, :edit, :update, :destroy]

  # GET /authorized_users
  # GET /authorized_users.json
  def index
    @authorized_users = AuthorizedUser.all
  end

  # GET /authorized_users/1
  # GET /authorized_users/1.json
  def show
  end

  # GET /authorized_users/new
  def new
    @authorized_user = AuthorizedUser.new
  end

  # GET /authorized_users/1/edit
  def edit
  end

  # POST /authorized_users
  # POST /authorized_users.json
  def create
    @authorized_user = AuthorizedUser.new(authorized_user_params)

    respond_to do |format|
      if @authorized_user.save
        format.html { redirect_to @authorized_user, notice: 'Authorized user was successfully created.' }
        format.json { render :show, status: :created, location: @authorized_user }
      else
        format.html { render :new }
        format.json { render json: @authorized_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorized_users/1
  # PATCH/PUT /authorized_users/1.json
  def update
    respond_to do |format|
      if @authorized_user.update(authorized_user_params)
        format.html { redirect_to @authorized_user, notice: 'Authorized user was successfully updated.' }
        format.json { render :show, status: :ok, location: @authorized_user }
      else
        format.html { render :edit }
        format.json { render json: @authorized_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorized_users/1
  # DELETE /authorized_users/1.json
  def destroy
    @authorized_user.destroy
    respond_to do |format|
      format.html { redirect_to authorized_users_url, notice: 'Authorized user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authorized_user
      @authorized_user = AuthorizedUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authorized_user_params
      params.require(:authorized_user).permit(:username, :password, :department, :date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def search
  end

  def match
  end

  def faq
  end

  def pricing
  end

  def features
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorized_users_helper.rb
module AuthorizedUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authorized_users/_form.html.erb
<%= form_for(@authorized_user) do |f| %>
  <% if @authorized_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorized_user.errors.count, "error") %> prohibited this authorized_user from being saved:</h2>

      <ul>
      <% @authorized_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorized_users/edit.html.erb
<h1>Editing authorized_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorized_user %> |
<%= link_to 'Back', authorized_users_path %>

app/views/authorized_users/index.html.erb
<h1>Listing authorized_users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Department</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authorized_users.each do |authorized_user| %>
      <tr>
        <td><%= authorized_user.username %></td>
        <td><%= authorized_user.password %></td>
        <td><%= authorized_user.department %></td>
        <td><%= authorized_user.date %></td>
        <td><%= link_to 'Show', authorized_user %></td>
        <td><%= link_to 'Edit', edit_authorized_user_path(authorized_user) %></td>
        <td><%= link_to 'Destroy', authorized_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authorized user', new_authorized_user_path %>

app/views/authorized_users/new.html.erb
<h1>New authorized_user</h1>

<%= render 'form' %>

<%= link_to 'Back', authorized_users_path %>

app/views/authorized_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @authorized_user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @authorized_user.password %>
</p>

<p>
  <strong>Department:</strong>
  <%= @authorized_user.department %>
</p>

<p>
  <strong>Date:</strong>
  <%= @authorized_user.date %>
</p>

<%= link_to 'Edit', edit_authorized_user_path(@authorized_user) %> |
<%= link_to 'Back', authorized_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forensity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p> Forensity: Swiss Forensic Solutions </p>
  <%= link_to "Home", root_path %>
  <%= link_to "Search", welcome_search_path %>
  <%= link_to "Match", welcome_match_path %>
  <%= link_to "About us", welcome_about_path %>
  <%= link_to "FAQs", welcome_faq_path %>
  <%= link_to "Contact us", welcome_contact_path %>
  <%= link_to "Features", welcome_features_path %>
   <%= link_to "Pricing", welcome_pricing_path %>
<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/match.html.erb
<h1>Welcome#match</h1>
<p>Find me in app/views/welcome/match.html.erb</p>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>

app/views/welcome/search.html.erb
<h1>Welcome#search</h1>
<p>Find me in app/views/welcome/search.html.erb</p>